package handler

import (
	"encoding/json"
	"net/http"

	"github.com/nightfixed/atelier-private-chef/api/internal/ai"
)

// NewCodexHandler handles POST /api/generate-codex.
// It accepts a CodexRequest (sensory profile from the Codex ritual) and returns
// a personalised tasting menu + atmospheric story generated by the AI provider.
func NewCodexHandler(provider ai.Provider) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			writeError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}

		var req ai.CodexRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeError(w, http.StatusBadRequest, "invalid JSON")
			return
		}
		if req.GuestName == "" {
			req.GuestName = "Oaspete"
		}

		resp, err := provider.GenerateCodex(r.Context(), req)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "codex generation failed")
			return
		}

		writeJSON(w, http.StatusOK, resp)
	})
}
